// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG3cEXfc9VOd_Wn5TN8g0D3uwIjF4bxYc',
    appId: '1:661096346139:web:0ffb2c7a3951753dacbebe',
    messagingSenderId: '661096346139',
    projectId: 'lab3-b30f4',
    authDomain: 'lab3-b30f4.firebaseapp.com',
    storageBucket: 'lab3-b30f4.appspot.com',
    measurementId: 'G-XWJC9RLPX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuj0OuA-EYbm6TIqMIqCsZ2t9z-1mR9Zk',
    appId: '1:661096346139:android:1d3041d282dbc185acbebe',
    messagingSenderId: '661096346139',
    projectId: 'lab3-b30f4',
    storageBucket: 'lab3-b30f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTS_QDN8JUUIyvvc-Rp2DmfickL1VjrRU',
    appId: '1:661096346139:ios:5ab2033b8f7c09b3acbebe',
    messagingSenderId: '661096346139',
    projectId: 'lab3-b30f4',
    storageBucket: 'lab3-b30f4.appspot.com',
    iosBundleId: 'com.example.lab3201084',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTS_QDN8JUUIyvvc-Rp2DmfickL1VjrRU',
    appId: '1:661096346139:ios:6d44aee1161bd3afacbebe',
    messagingSenderId: '661096346139',
    projectId: 'lab3-b30f4',
    storageBucket: 'lab3-b30f4.appspot.com',
    iosBundleId: 'com.example.lab3201084.RunnerTests',
  );
}
